### ISSUE TITLE
Manual focus magnification property not setable via ethernet control

### ISSUE THREAD

**Issue by Christoph460** [imaginevision/Z-Camera-Doc#30]
Controlling the camera via HTTP API, where a key is listed with 

> mf_mag

is not possible. If I send the command `http://ip/ctrl/get?k=mf_mag` i receive the message 

> key is not supported

What am I doing wrong?

**Comment by ailike** [comment]
What response do you want from camera? Mag the preview?

**Comment by ailike** [comment]
We check the code, there is some bug in the latest version, please use mf_assist on 0.84

**Comment by Christoph460** [comment]
Alright thanks

**Comment by dia3olik** [comment]
I think the issue should be closed only when solved in the code...if there is a bug it should stay open until the bug is ironed out...

**Comment by ailike** [comment]
We will make it to "k=mf_mag" in the comming release.

**Comment by ailike** [comment]
supported in latest release
