### ISSUE TITLE
Return filename when recording stop

### ISSUE THREAD

**Issue by onomonomedia** [imaginevision/Z-Camera-Doc#31]
When I stop a recording from the api would it be possible to have it return the file name of the recording?

Currently we get a confirmation but it would be nice if we could have the filename returned in the msg.
```
{
    "code": 0,
    "desc": "",
    "msg": ""
}
```

**Comment by ailike** [comment]
/ctrl/get?k=last_file_name

**Comment by onomonomedia** [comment]
That works.  Thank you!
