### ISSUE TITLE
CORS headers

### ISSUE THREAD

**Issue by qhulamm** [imaginevision/Z-Camera-Doc#34]
I've built a web application to control the zcam e2 for my project.  I'm having issues running it though because the camera does not send the CORS headers which does not allow my application to access/control the camera.  I'm using Chrome to run my app.  Can this be added?

**Comment by ailike** [comment]
Noted

**Comment by cscarfie** [comment]
Has there been any resolution to the CORS policy issue?  I am building a browser based client for the E2C and am running into the same problem.  .htaccess file is missing on the camera to allow wildcard CORS access.  Any way to load up a custom .htaccess file?

**Comment by rlamarche** [comment]
A solution could be to run a proxy that send the CORS headers.

**Comment by ailike** [comment]
Already supported in latest release.
