### ISSUE TITLE
Z CAM E2 How to pull stream0/1？

### ISSUE THREAD

**Issue by huaerduoduokaibuting** [imaginevision/Z-Camera-Doc#44]
**GET /ctrl/set?send_stream=Stream0
GET /ctrl/set?send_stream=Stream1**

1 - At present, I want to develop a pull-stream application by myself, but the push-pull stream program provided on the official website is not applicable.

2 - I saw in the http protocol that stream0/1 can be set. But how can I get to stream1?

3 - Is this stream1 using http streaming protocol? If my assumption is correct! Then I just need to know the http url of stream1! But I tried a lot of methods, and I couldn't pull to stream1.

4 - Is there a problem with my understanding? Or can you give relevant reference materials to pull stream1.
Thank.

**Comment by ailike** [comment]
It's ssp only
