### ISSUE TITLE
Questions about Z CAM E2G camera multi-device synchronization function?

### ISSUE THREAD

**Issue by HongShiKuan** [imaginevision/Z-Camera-Doc#47]
Hello. Excuse me
At present, I use the libssp protocol and want to obtain simultaneous streaming of multiple Z CAM E2G cameras. However, the data obtained by the discovery is not completely ms-level synchronization. There is always a frame gap.

1-Does the multi-cam synchronization function of Z CAM E2G camera only support simultaneous recording to SD card? Whether to support the use of libssp protocol to pull multi-camera synchronous streaming data

2-If libssp is supported, can I get simultaneous streaming data as long as I ensure that multiple cameras get the same h264->frm_no at the same time?

3-If libssp pull synchronous stream function exists, whether additional opening action is required.

4-If the libssp protocol does not support the synchronization data of multiple cameras, is there any other way to obtain synchronization data?

**Comment by litianfa** [comment]
Hello, are you solve this problem? @HongShiKuan
