### ISSUE TITLE
Streaming API

### ISSUE THREAD

**Issue by albertmatyi** [imaginevision/Z-Camera-Doc#5]
Streaming API is listed in the bulletpoints, but there is no dedicated section describing how it works

Would you elaborate how one can use streaming?

**Comment by benhinchley** [comment]
It is now documented here https://github.com/imaginevision/Z-Camera-Doc/blob/master/http.md#streaming

**Comment by benhinchley** [comment]
@danielawd https://github.com/imaginevision/Z-Camera-Doc/blob/master/E1/http.md#streaming
or for the E2 https://github.com/imaginevision/Z-Camera-Doc/blob/master/E2/http.md#Network-streaming
