### ISSUE TITLE
get lens_focus_pos key value

### ISSUE THREAD

**Issue by adahbingee** [imaginevision/Z-Camera-Doc#61]
Please add the key value.

```
GET /ctrl/get?lens_focus_pos
GET /ctrl/get?lens_zoom_pos
```

![image](https://user-images.githubusercontent.com/2985536/168717568-6484da10-a5aa-4d55-a600-efba15dbcb6d.png)

**Comment by costavale** [comment]
Did you manage to understand what are supposed to be the values? and if the values are the same as mf_drive?

**Comment by adahbingee** [comment]
It' works

command to get focus position
```
/ctrl/get?k=lens_focus_pos
```

for setting focus command
```
/ctrl/set?lens_focus_pos=100
```

**Comment by costavale** [comment]
Thank you! I have seen that this is working, but what does the number "100" in `/ctrl/set?lens_focus_pos=100` means? and what is the difference to `/ctrl/set?mf_drive=100`

**Comment by adahbingee** [comment]
sorry, that's just an experienced value

**Comment by costavale** [comment]
Ok, and what is the difference with mf_drive?

**Comment by adahbingee** [comment]
I did not use this command yet.
sorry

**Comment by costavale** [comment]
Ok, thank you!
